#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run linters on staged files
npx lint-staged
# Run forge snapshot to build contracts and get gas report
forge snapshot
# Stage the snapshot
git add .gas-snapshot