#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run linters on staged files
npx lint-staged
# Run forge snapshot to build contracts and get gas report
FOUNDRY_FUZZ_MAX_TEST_REJECTS=1000000 forge snapshot
# Stage the snapshot
git add .gas-snapshot